### ISSUE TITLE
getImageData throwing exception

### ISSUE THREAD

**Issue by meltingice** [play-co/webgl-2d#10]
No matter what I do, the call to getImageData() seems to throw the awesomely vague exception "Uncaught TypeError: Type error" on line 516.

The code looks like this:

```
this.canvas = canvas;
if ('WebGL2D' in window) {
    console.log("WebGL-2D Enabled!");
    WebGL2D.enable(this.canvas);
    this.context = canvas.getContext("webgl-2d");
} else {
    this.context = canvas.getContext("2d");
}

this.context.drawImage(image, 0, 0, image.width, image.height);

this.image_data = this.context.getImageData(0, 0, image.width, image.height);
```

**Comment by meltingice** [comment]
It looks like the problem is with gl.readPixels(). The last argument expects an ArrayBufferView type array, which is not satisfied by the CanvasPixelArray. Passing in a Float32Array stops the code from breaking, but turns the image black in the end.

**Comment by secretrobotron** [comment]
Thanks for the catch. Which browser are you using?

**Comment by secretrobotron** [comment]
meltingice, this commit should fix your problem. Please let me know if it doesn't.

 https://github.com/corbanbrook/webgl-2d/commit/6c5beef7a43cb0faa1875653db246e0f46692b9e

**Comment by meltingice** [comment]
It did! Everything works as expected now :)

Not sure if there's any room for improvement in regards to speed, but every filter in CamanJS performed slightly slower except for gamma.

Without webgl-2d: http://cl.ly/3k2f0V0T0m0o2h3N1J1a

With webgl-2d: http://cl.ly/3a3z3D1R1k1D2a2j0626

**Comment by secretrobotron** [comment]
We're actually in the process of benchmarking. It's a new project, so while speed is an obvious concern, we've still got work to do.

One of the issues we're going to have to face is libraries like CamanJS. We know we can speed up certain parts of canvas very obviously with WebGL, but there are some applications at which we'll have to look more carefully.

Without looking into it very carefully, I assume that CamanJS is doing a getImageData, manipulating it, and then placing it back with putImageData. Depending on the structure of their code, that process will weight down on our current system.

**Comment by meltingice** [comment]
Yep, that's the gist of it. Mainly just a lot of loops doing pixel-wise math operations :P

**Comment by corbanbrook** [comment]
In this case I don't see how webGL can speed things up. The get/putImageData process in WebGL2D is adding more overhead. And any speed improvements you would gain from the drawing are negated if the imageData is changing each frame. 

Speed improvements are had when we can cache an image as a texture and then reuse it like sprites.

**Comment by meltingice** [comment]
Ok that makes sense. I had a feeling that would be the case. Thanks anyways!

**Comment by corbanbrook** [comment]
I would suspect the best place to get performance wins in CamanJS is to switch away from your color object:

color = {
        r: arguments[0],
        g: arguments[1],
        b: arguments[2]
      };

and use a color int with bit masks or just a normal array instead.
