### ISSUE TITLE
Weird output

### ISSUE THREAD

**Issue by Irrelon** [play-co/webgl-2d#22]
Hi, I'm the developer of the Isogenic Game Engine and I thought it would be cool to test webgl-2d on our engine.

I've got some questions that might lead to a bug fix here.

Please check the screenshot here: http://www.isogenicengine.com/wp-content/uploads/2011/05/webgl-2d-bug.png

The image actually displays proper graphics for about 50 milliseconds then goes into this ghosted image view. My first suspicion is that upon resizing the canvas (which Isogenic does automatically when the browser loads and when it is resized) may be causing this issue. Does webgl-2d support changing the size of the canvas AFTER the context has been set up?

If I turn off automatic resizing of the canvas to fill the browser, all I get is a big white screen where I assume the clearRect cleared the canvas but nothing is drawn after that! This may also have something to do with the issue about the hearts not being <a href="https://github.com/corbanbrook/webgl-2d/issues/21">drawn in the drawImage example</a> - in that example the canvas stays completely white as well.

The expected result (and how it looks with the '2d' context is this): http://www.isogenicengine.com/wp-content/uploads/2011/05/webgl-2d-bug2.png - That shot has auto-resize of the canvas turned off, the first DOES NOT so although you see a similar sized box, the canvas actually fills up the entire screen in the first shot, this is why I was leaning to a resize issue, like the size of the redraw area stayed the same even after resizing the canvas.

All tests run in Chrome 11.0.696.65

Any thoughts? I would be happy to investigate further and post bug fixes if I can help out!

**Comment by richardanaya** [comment]
I'm also interested in resolving this issue. =)

**Comment by Irrelon** [comment]
@Richardanaya Do you also resize your canvas and then experience this issue? It would be good to see if that is the underlying cause of the ghosting problem.
