### ISSUE TITLE
Is there a Roadmap?

### ISSUE THREAD

**Issue by jonobr1** [play-co/webgl-2d#3]
I tried pluggin' in a couple of old stuff and it's pretty flawless! I was wondering what you guys had plan to implement / not. Like for example `save()`, `restore()`, or `clearRect()`???

Really awesome — saves lotsa time

^^

**Comment by corbanbrook** [comment]
I am roughly looking at next week to have many of the Canvas2D API implemented.

most of the code is already done in the processing-js project so it is really just a matter of organizing it together.

**Comment by ghost** [comment]
corban: If you can get putImageData working very well at even 60 fps for something like a 400x400 res canvas with single digit CPU usage, I'd be very interested.

**Comment by corbanbrook** [comment]
We are preparing a road map for the project and a timeline for features to be completely. This should be appearing on the wiki shortly.
