### ISSUE TITLE
Unit Tests

### ISSUE THREAD

**Issue by rwaldron** [play-co/webgl-2d#4]
Contribution to this project seems unfortunately limited due the lack of a test suite. Are there any plans to include a definitive unit test suite?

**Comment by corbanbrook** [comment]
Yes. currently example.html is the only ref test but as more functionality is added so will more tests.

**Comment by rwaldron** [comment]
If I were to drop in a starting test suite and write some basic assertions for the API, would this be something you'd be interested in pulling in?

**Comment by corbanbrook** [comment]
Sorry for the late reply. Yes, a test suite would be great. I have currently made an example directory where I hope to place very terse tests for each function (currently the examples are not very terse and include a lot of different features in each).

There is also a benchmark dir where we will be comparing frameRate between Canvas2D and WebGL2D.

Wpi;d ;pve upir input on this.

re,
corban

**Comment by corbanbrook** [comment]
David Humphrey added the HTML5.org unit test suite which is working out quite well for tracking down various edge cases.
