### ISSUE TITLE
fillStyle and strokeStyle do not support hex color or color constants

### ISSUE THREAD

**Issue by corbanbrook** [play-co/webgl-2d#6]
fillStyle and strokeStyle currently only support rgb and rgba css color strings. 

Add support for hex color, ie. "#990066" and color constants, ie. "orange"

**Comment by bebraw** [comment]
Feel free to get the color name and hex code from this gist, https://gist.github.com/858869 . Hope that helps. :)

**Comment by corbanbrook** [comment]
Thanks. will do :)

**Comment by corbanbrook** [comment]
I added #fff and #ffffff hex3 and hex6 color support as well as % support for rgb color.

Still need to add hsla and color keywords.
